### ISSUE TITLE
two date fields

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/book-of-n3c-v1#103]
distinguish the "version 1 first published date" from the "most recent change date"

suggested by @JohannaLoomba

**Comment by wibeasley** [comment]
@JohannaLoomba, how do you feel about this callout at the bottom of each chapter?

![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/9b6fcf46-20b2-4e2a-bd4c-224ac56e6691)

**Comment by JohannaLoomba** [comment]
Hi Will – this is good, but if contributions come through github do we need to name the corresponding author? I am open to it, but just wondering.
